Character.create(first_name: "Harry", last_name: "Potter", gender: "male", house: "Gryffindor")
Character.create(first_name: "Hermione", last_name: "Granger", gender: "female", house: "Gryffindor")
Character.create(first_name: "Ron", last_name: "Weasley", gender: "male", house: "Gryffindor")
Character.create(first_name: "Ginny", last_name: "Weasley", gender: "female", house: "Gryffindor")
Character.create(first_name: "Draco", last_name: "Malfoy", gender: "male", house: "Slytherin")
Character.create(first_name: "Luna", last_name: "Lovegood", gender: "female", house: "Ravenclaw")
